all:
  hosts:
    node1:
      ansible_host: 3.136.209.152
      ansible_user: centos
      ansible_ssh_private_key_file: /path/to/key
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
